const Actions = {
  FILTER_CHANGE: 'FILTER_CHANGE',
  SORTING_CHANGE: 'SORTING_CHANGE',
  POINT_UPDATE: 'POINT_UPDATE',
  POINT_DELETE: 'POINT_DELETE',
  POINT_ADD: 'POINT_ADD',
  MODE_CHANGE: 'MODE_CHANGE',
  DATA_LOADED: 'DATA_LOADED',
  DATA_ERROR: 'DATA_ERROR',
};

export default Actions;
